---
title: Kiko Now
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Kiko Now
description: Web Developer from Somewhere
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
navigation:
- name: Blog
  url: "/"
- name: About
  url: "/about"
- name: Archive
  url: "/archive"
- name: Tags
  url: "/tags"
- name: Theme
  url: https://github.com/AWEEKJ/kiko-now
paginate: 5
footer-links:
  behance: 
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: AWEEKJ/kiko-now
  googleplus: 
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  stackoverflow: 
  tumblr: 
  twitter: jekyllrb
  youtube: 
footer-text: "© 2017 Kiko Now"
disqus: 
google_analytics: 
url: 
baseurl: 
permalink: "/:title/"
paginate_path: "/page:num/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
